Fix baseurl issue

diff --git a/.github/workflows/deploy-gh-pages.yml b/.github/workflows/deploy-gh-pages.yml
--- a/.github/workflows/deploy-gh-pages.yml
+++ b/.github/workflows/deploy-gh-pages.yml
@@ -29,7 +29,7 @@ jobs:
         uses: actions/setup-node@v3
 
       - name: Install dependencies
-        run: yarn || true
+        run: yarn || true #Fails because of some unimportant error (Well unimportant for now)
 
       - name: Build project
         run: |
